apiVersion: v1
kind: Namespace
metadata:
  name: inference
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-ksa
  namespace: inference
  annotations:
    iam.gke.io/gcp-service-account: gke-inference-sa@efficient-inference-506713.iam.gserviceaccount.com
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: inference
type: Opaque
stringData:
  token: "" # Populate with your HF token if accessing gated models (e.g. Gemma 2)
