apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: vllm-pod-monitoring
  namespace: inference
spec:
  selector:
    matchLabels:
      app: vllm-server
  endpoints:
  - port: 8000
    interval: 15s
    path: /metrics
