apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vllm-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllm-server
  minReplicaCount: 0
  maxReplicaCount: 2
  cooldownPeriod: 3600 # 1 hour (3600 seconds) of inactivity before scaling down to 0
  pollingInterval: 15
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://frontend.default.svc.cluster.local:9090
      metricName: vllm_num_requests_waiting
      query: sum(vllm_num_requests_waiting)
      threshold: '1'
      ignoreNullValues: "false"
